import Foundation

// Stable identifier used for both the macOS LaunchAgent label and Nix-managed defaults suite.
// nix-astroclaw writes app defaults into this suite to survive app bundle identifier churn.
let launchdLabel = "ai.astroclaw.mac"
let gatewayLaunchdLabel = "ai.astroclaw.gateway"
let onboardingVersionKey = "astroclaw.onboardingVersion"
let onboardingSeenKey = "astroclaw.onboardingSeen"
let currentOnboardingVersion = 7
let pauseDefaultsKey = "astroclaw.pauseEnabled"
let iconAnimationsEnabledKey = "astroclaw.iconAnimationsEnabled"
let swabbleEnabledKey = "astroclaw.swabbleEnabled"
let swabbleTriggersKey = "astroclaw.swabbleTriggers"
let voiceWakeTriggerChimeKey = "astroclaw.voiceWakeTriggerChime"
let voiceWakeSendChimeKey = "astroclaw.voiceWakeSendChime"
let showDockIconKey = "astroclaw.showDockIcon"
let defaultVoiceWakeTriggers = ["astroclaw"]
let voiceWakeMaxWords = 32
let voiceWakeMaxWordLength = 64
let voiceWakeMicKey = "astroclaw.voiceWakeMicID"
let voiceWakeMicNameKey = "astroclaw.voiceWakeMicName"
let voiceWakeLocaleKey = "astroclaw.voiceWakeLocaleID"
let voiceWakeAdditionalLocalesKey = "astroclaw.voiceWakeAdditionalLocaleIDs"
let voicePushToTalkEnabledKey = "astroclaw.voicePushToTalkEnabled"
let voiceWakeTriggersTalkModeKey = "astroclaw.voiceWakeTriggersTalkMode"
let talkEnabledKey = "astroclaw.talkEnabled"
let talkPhaseSoundsEnabledKey = "astroclaw.talkPhaseSoundsEnabled"
let talkShiftToStopEnabledKey = "astroclaw.talkShiftToStopEnabled"
let iconOverrideKey = "astroclaw.iconOverride"
let connectionModeKey = "astroclaw.connectionMode"
let remoteTargetKey = "astroclaw.remoteTarget"
let remoteIdentityKey = "astroclaw.remoteIdentity"
let remoteProjectRootKey = "astroclaw.remoteProjectRoot"
let remoteCliPathKey = "astroclaw.remoteCliPath"
let canvasEnabledKey = "astroclaw.canvasEnabled"
let cameraEnabledKey = "astroclaw.cameraEnabled"
let systemRunPolicyKey = "astroclaw.systemRunPolicy"
let systemRunAllowlistKey = "astroclaw.systemRunAllowlist"
let systemRunEnabledKey = "astroclaw.systemRunEnabled"
let locationModeKey = "astroclaw.locationMode"
let locationPreciseKey = "astroclaw.locationPreciseEnabled"
let peekabooBridgeEnabledKey = "astroclaw.peekabooBridgeEnabled"
let deepLinkKeyKey = "astroclaw.deepLinkKey"
let modelCatalogPathKey = "astroclaw.modelCatalogPath"
let modelCatalogReloadKey = "astroclaw.modelCatalogReload"
let cliInstallPromptedVersionKey = "astroclaw.cliInstallPromptedVersion"
let heartbeatsEnabledKey = "astroclaw.heartbeatsEnabled"
let debugPaneEnabledKey = "astroclaw.debugPaneEnabled"
let debugFileLogEnabledKey = "astroclaw.debug.fileLogEnabled"
let appLogLevelKey = "astroclaw.debug.appLogLevel"
let voiceWakeSupported: Bool = ProcessInfo.processInfo.operatingSystemVersion.majorVersion >= 26
