export const browserCoreExamples = [
  "astroclaw browser status",
  "astroclaw browser start",
  "astroclaw browser start --headless",
  "astroclaw browser stop",
  "astroclaw browser tabs",
  "astroclaw browser open https://example.com",
  "astroclaw browser focus abcd1234",
  "astroclaw browser close abcd1234",
  "astroclaw browser screenshot",
  "astroclaw browser screenshot --full-page",
  "astroclaw browser screenshot --ref 12",
  "astroclaw browser snapshot",
  "astroclaw browser snapshot --format aria --limit 200",
  "astroclaw browser snapshot --efficient",
  "astroclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "astroclaw browser navigate https://example.com",
  "astroclaw browser resize 1280 720",
  "astroclaw browser click 12 --double",
  "astroclaw browser click-coords 120 340",
  'astroclaw browser type 23 "hello" --submit',
  "astroclaw browser press Enter",
  "astroclaw browser hover 44",
  "astroclaw browser drag 10 11",
  "astroclaw browser select 9 OptionA OptionB",
  "astroclaw browser upload /tmp/astroclaw/uploads/file.pdf",
  'astroclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "astroclaw browser dialog --accept",
  'astroclaw browser wait --text "Done"',
  "astroclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "astroclaw browser console --level error",
  "astroclaw browser pdf",
];
